export const RATE_PROFILE = 'RATE_PROFILE';
export const UPDATE_MY_PROFILE = 'UPDATE_MY_PROFILE';
export const LOAD_LANGUAGE = 'LOAD_LANGUAGE';
export const LOAD_LIST_LANGUAGES = 'LOAD_LIST_LANGUAGES';
export const TOGGLE_MENU_OPEN = 'TOGGLE_MENU_OPEN';
export const SET_RATE_INFO_PROFILE = 'SET_RATE_INFO_PROFILE';
export const RESET_RATE_INFO_PROFILE = 'RESET_RATE_INFO_PROFILE';
