export const LOAD_PROFILES_TO_SEARCH = 'LOAD_PROFILES_TO_SEARCH';
export const SWIPE_NEXT_PROFILE = 'SWIPE_NEXT_PROFILE';
export const SEND_REQUEST_PROFILE = 'SEND_REQUEST_PROFILE';
export const LIKE_PROFILE = 'LIKE_PROFILE';
