export const LOAD_PROFILES_TO_SEARCH = 'LOAD_PROFILES_TO_SEARCH';
export const SWIPE_PROFILE = 'SWIPE_PROFILE';
export const UPDATE_GALLERY_INDEX_PROFILE_SEARCH = 'UPDATE_GALLERY_INDEX_PROFILE_SEARCH';
export const SEND_REQUEST_PROFILE = 'SEND_REQUEST_PROFILE';
export const LIKE_PROFILE = 'LIKE_PROFILE';
